author: "Hermann Mayer <hermann.mayer92@gmail.com>"
category: "admin"
summary: "Acknowledge readed messages and ask for them"
home: "https://github.com/hausgold/ejabberd-read-markers"
url: "git@github.com:hausgold/ejabberd-read-markers.git"
